version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        NEXT_PUBLIC_API_URL: http://backend:3001
        NEXT_PUBLIC_NODE_ENV: production
        NEXT_PUBLIC_PORT: 3000
    ports:
      - "7663:3000"
    depends_on:
      - backend
    networks:
      - muse-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7664:3001"
    networks:
      - muse-network

networks:
  muse-network:
    driver: bridge
