'use client';

import { useState } from 'react';
import toast from 'react-hot-toast';
import { twoFactorService } from '@/services/twoFactorService';

interface Manage2FAProps {
  twoFAStatus: {
    backupCodesCount: number;
  };
  onClose: () => void;
}

export default function Manage2FA({ twoFAStatus }: Manage2FAProps) {
  const [backupCodes, setBackupCodes] = useState<string[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [showBackupCodes, setShowBackupCodes] = useState(false);

  const handleViewBackupCodes = async () => {
    try {
      setIsLoading(true);
      const codes = await twoFactorService.getBackupCodes();
      setBackupCodes(codes.backupCodes);
      setShowBackupCodes(true);
      toast.success('Backup codes displayed');
      
      // Auto-hide backup codes after 30 seconds for security
      setTimeout(() => {
        setShowBackupCodes(false);
        setBackupCodes([]);
        toast.success('Backup codes hidden for security');
      }, 30000);
    } catch {
      toast.error('Failed to get backup codes');
    } finally {
      setIsLoading(false);
    }
  };

  const handleRegenerateBackupCodes = async () => {
    try {
      setIsLoading(true);
      const codes = await twoFactorService.regenerateBackupCodes();
      setBackupCodes(codes.backupCodes);
      setShowBackupCodes(true);
      toast.success('New backup codes generated');
    } catch {
      toast.error('Failed to regenerate backup codes');
    } finally {
      setIsLoading(false);
    }
  };

  const handleDownloadBackupCodes = () => {
    const content = `MuseMusic - Two-Factor Authentication Backup Codes
Generated: ${new Date().toLocaleString()}

IMPORTANT: Save these codes in a safe place!

Your backup codes:
${backupCodes.map((code, index) => `${index + 1}. ${code}`).join('\n')}

Instructions:
- Each code can only be used once
- Use these codes if you lose access to your authenticator app
- Store them securely (password manager, encrypted file, etc.)
- Do not share these codes with anyone

If you lose all backup codes, contact support to regain access to your account.

---
Generated by MuseMusic Security System`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `muse-music-backup-codes-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success('Backup codes downloaded!');
  };

  return (
    <div className="space-y-6">
      <div className="text-center">
        <h3 className="text-lg font-medium text-gray-900 mb-2">Manage 2FA</h3>
        <p className="text-sm text-gray-600 mb-4">
          You have {twoFAStatus.backupCodesCount} backup codes remaining.
        </p>
      </div>
      
      <div className="space-y-3">
        <button
          onClick={handleViewBackupCodes}
          disabled={isLoading}
          className="w-full bg-blue-100 text-blue-700 py-3 rounded-lg hover:bg-blue-200 transition-colors disabled:bg-gray-100 disabled:text-gray-400"
        >
          {isLoading ? 'Loading...' : 'View Backup Codes'}
        </button>
        
        <button
          onClick={handleRegenerateBackupCodes}
          disabled={isLoading}
          className="w-full bg-orange-100 text-orange-700 py-3 rounded-lg hover:bg-orange-200 transition-colors disabled:bg-gray-100 disabled:text-gray-400"
        >
          {isLoading ? 'Generating...' : 'Generate New Backup Codes'}
        </button>
      </div>

      {showBackupCodes && (
        <div className="p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
          <h4 className="font-medium text-gray-900 mb-2">Your Backup Codes</h4>
          <p className="text-xs text-gray-700 mb-3">
            Save these codes in a safe place. Each code can only be used once.
          </p>
          <div className="grid grid-cols-2 gap-2 text-sm font-mono">
            {backupCodes.map((code, index) => (
              <div key={index} className="bg-white p-2 rounded border text-center text-gray-900 font-mono">
                {code}
              </div>
            ))}
          </div>
          <div className="flex space-x-2 mt-3">
            <button
              onClick={handleDownloadBackupCodes}
              className="flex-1 px-4 py-2 bg-blue-600 text-white text-sm rounded-lg hover:bg-blue-700 transition-colors flex items-center justify-center space-x-2"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              <span>Download</span>
            </button>
            <button
              onClick={() => {
                setShowBackupCodes(false);
                setBackupCodes([]);
              }}
              className="flex-1 px-4 py-2 bg-gray-500 text-white text-sm rounded-lg hover:bg-gray-600 transition-colors"
            >
              Hide Codes
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
