'use client';

import { useState, useCallback, useEffect } from 'react';
import Image from 'next/image';
import toast from 'react-hot-toast';
import { twoFactorService } from '@/services/twoFactorService';

interface Setup2FAProps {
  onComplete: () => void;
  onClose: () => void;
}

export default function Setup2FA({ onComplete, onClose }: Setup2FAProps) {
  const [step, setStep] = useState<'qr' | 'verify' | 'backup' | 'complete'>('qr');
  const [qrCode, setQrCode] = useState<string>('');
  const [manualKey, setManualKey] = useState<string>('');
  const [verificationCode, setVerificationCode] = useState<string>('');
  const [backupCodes, setBackupCodes] = useState<string[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [showBackupCodes, setShowBackupCodes] = useState(false);
  const [copied, setCopied] = useState(false);

  const initializeSetup = useCallback(async () => {
    try {
      setIsLoading(true);
      const setupData = await twoFactorService.setup2FA();
      setQrCode(setupData.qrCode);
      setManualKey(setupData.manualEntryKey);
      setStep('qr');
    } catch (error) {
      console.error('Setup 2FA error:', error);
      toast.error('Failed to initialize 2FA setup');
      onClose();
    } finally {
      setIsLoading(false);
    }
  }, [onClose]);

  const handleVerifyCode = async () => {
    if (!verificationCode || verificationCode.length !== 6) {
      toast.error('Please enter a valid 6-digit code');
      return;
    }

    try {
      setIsLoading(true);
      await twoFactorService.verifySetupCode(verificationCode);
      setStep('backup');
    } catch (error) {
      console.error('Verify code error:', error);
      toast.error('Invalid verification code. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleGenerateBackupCodes = async () => {
    try {
      setIsLoading(true);
      const codes = await twoFactorService.generateBackupCodes();
      setBackupCodes(codes.backupCodes);
      setShowBackupCodes(true);
      setStep('complete');
    } catch (error) {
      console.error('Generate backup codes error:', error);
      toast.error('Failed to generate backup codes');
    } finally {
      setIsLoading(false);
    }
  };

  const handleCopyKey = async () => {
    try {
      await navigator.clipboard.writeText(manualKey);
      setCopied(true);
      toast.success('Manual key copied to clipboard!');
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      console.error('Failed to copy:', error);
      toast.error('Failed to copy key');
    }
  };

  const handleDownloadBackupCodes = () => {
    const content = `MuseMusic - Two-Factor Authentication Backup Codes
Generated: ${new Date().toLocaleString()}

IMPORTANT: Save these codes in a safe place!

Your backup codes:
${backupCodes.map((code, index) => `${index + 1}. ${code}`).join('\n')}

Instructions:
- Each code can only be used once
- Use these codes if you lose access to your authenticator app
- Store them securely (password manager, encrypted file, etc.)
- Do not share these codes with anyone

If you lose all backup codes, contact support to regain access to your account.

---
Generated by MuseMusic Security System`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `muse-music-backup-codes-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success('Backup codes downloaded!');
  };

  const handleComplete = () => {
    onComplete();
  };

  // Initialize setup when component mounts
  useEffect(() => {
    initializeSetup();
  }, [initializeSetup]);

  return (
    <div className="space-y-6">
      {/* QR Code Step */}
      {step === 'qr' && (
        <div className="space-y-6">
          <div className="text-center">
            <h3 className="text-lg font-medium text-gray-900 mb-2">Scan QR Code</h3>
            <p className="text-sm text-gray-600 mb-4">
              Use your authenticator app to scan this QR code
            </p>
            
            {isLoading ? (
              <div className="flex items-center justify-center h-64">
                <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-[#7B61FF]"></div>
              </div>
            ) : qrCode ? (
              <div className="flex justify-center">
                <Image
                  src={qrCode}
                  alt="QR Code"
                  width={200}
                  height={200}
                  className="border rounded-lg"
                />
              </div>
            ) : (
              <div className="flex items-center justify-center h-64 text-gray-500">
                <p>Failed to load QR code</p>
              </div>
            )}
            
            <div className="mt-4 p-3 bg-gray-50 rounded-lg">
              <p className="text-xs text-gray-700 mb-2 font-medium">Or enter this key manually:</p>
              <div className="relative">
                <code className="text-sm font-mono bg-white p-2 pr-10 rounded border block break-all text-gray-800">
                  {manualKey}
                </code>
                <button
                  onClick={handleCopyKey}
                  className="absolute right-2 top-1/2 transform -translate-y-1/2 text-gray-500 hover:text-gray-700 transition-colors"
                  title="Copy to clipboard"
                >
                  {copied ? (
                    <svg className="w-4 h-4 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                    </svg>
                  ) : (
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                    </svg>
                  )}
                </button>
              </div>
            </div>
          </div>
          
          <button
            onClick={() => setStep('verify')}
            className="w-full bg-[#7B61FF] text-white py-3 rounded-lg hover:bg-[#6B51EF] transition-colors"
          >
            I&apos;ve scanned the QR code
          </button>
        </div>
      )}

      {/* Verify Step */}
      {step === 'verify' && (
        <div className="space-y-6">
          <div>
            <h3 className="text-lg font-medium text-gray-900 mb-2">Verify Setup</h3>
            <p className="text-sm text-gray-600 mb-4">
              Enter the 6-digit code from your authenticator app
            </p>
            
            <input
              type="text"
              value={verificationCode}
              onChange={(e) => setVerificationCode(e.target.value.replace(/\D/g, '').slice(0, 6))}
              placeholder="123456"
              className="w-full px-4 py-3 border border-gray-300 rounded-lg text-center text-lg font-mono tracking-widest text-gray-900 bg-white focus:outline-none focus:ring-2 focus:ring-[#7B61FF] focus:border-transparent"
              maxLength={6}
            />
          </div>
          
          <button
            onClick={handleVerifyCode}
            disabled={isLoading || verificationCode.length !== 6}
            className="w-full bg-[#7B61FF] text-white py-3 rounded-lg hover:bg-[#6B51EF] transition-colors disabled:bg-gray-400 disabled:cursor-not-allowed"
          >
            {isLoading ? 'Verifying...' : 'Verify Code'}
          </button>
        </div>
      )}

      {/* Backup Codes Step */}
      {step === 'backup' && (
        <div className="space-y-6">
          <div className="text-center">
            <h3 className="text-lg font-medium text-gray-900 mb-2">Generate Backup Codes</h3>
            <p className="text-sm text-gray-600 mb-4">
              Backup codes can be used to access your account if you lose your authenticator device.
              Store them in a safe place.
            </p>
          </div>
          
          <button
            onClick={handleGenerateBackupCodes}
            disabled={isLoading}
            className="w-full bg-[#7B61FF] text-white py-3 rounded-lg hover:bg-[#6B51EF] transition-colors disabled:bg-gray-400 disabled:cursor-not-allowed"
          >
            {isLoading ? 'Generating...' : 'Generate Backup Codes'}
          </button>
        </div>
      )}

      {/* Complete Step */}
      {step === 'complete' && (
        <div className="space-y-6">
          <div className="text-center">
            <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <svg className="w-8 h-8 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
            </div>
            <h3 className="text-lg font-medium text-gray-900 mb-2">2FA Setup Complete!</h3>
            <p className="text-sm text-gray-600 mb-4">
              Your account is now protected with two-factor authentication.
            </p>
          </div>

          {showBackupCodes && (
            <div className="p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
              <h4 className="font-medium text-gray-900 mb-2">Your Backup Codes</h4>
              <p className="text-xs text-gray-700 mb-3">
                Save these codes in a safe place. Each code can only be used once.
              </p>
              <div className="grid grid-cols-2 gap-2 text-sm font-mono">
                {backupCodes.map((code, index) => (
                  <div key={index} className="bg-white p-2 rounded border text-center text-gray-900 font-mono">
                    {code}
                  </div>
                ))}
              </div>
              <button
                onClick={handleDownloadBackupCodes}
                className="mt-3 w-full px-4 py-2 bg-blue-600 text-white text-sm rounded-lg hover:bg-blue-700 transition-colors flex items-center justify-center space-x-2"
              >
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
                <span>Download Backup Codes</span>
              </button>
            </div>
          )}
          
          <button
            onClick={handleComplete}
            className="w-full bg-[#7B61FF] text-white py-3 rounded-lg hover:bg-[#6B51EF] transition-colors"
          >
            Done
          </button>
        </div>
      )}
    </div>
  );
}
